INSERT INTO counties (rs, county_name, type, parent) VALUES (0, 'Deutschland', 'Staat', null);
INSERT INTO counties (rs, county_name, type, parent) VALUES (1, 'Schleswig-Holstein', 'Bundesland', 0);
INSERT INTO counties (rs, county_name, type, parent) VALUES (2, 'Hamburg', 'Bundesland', 0);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3, 'Niedersachsen', 'Bundesland', 0);
INSERT INTO counties (rs, county_name, type, parent) VALUES (4, 'Bremen', 'Bundesland', 0);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5, 'Nordrhein-Westfalen', 'Bundesland', 0);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6, 'Hessen', 'Bundesland', 0);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7, 'Rheinland-Pfalz', 'Bundesland', 0);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8, 'Baden-Württemberg', 'Bundesland', 0);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9, 'Bayern', 'Bundesland', 0);
INSERT INTO counties (rs, county_name, type, parent) VALUES (10, 'Saarland', 'Bundesland', 0);
INSERT INTO counties (rs, county_name, type, parent) VALUES (11, 'Berlin', 'Bundesland', 0);
INSERT INTO counties (rs, county_name, type, parent) VALUES (12, 'Brandenburg', 'Bundesland', 0);
INSERT INTO counties (rs, county_name, type, parent) VALUES (13, 'Mecklenburg-Vorpommern', 'Bundesland', 0);
INSERT INTO counties (rs, county_name, type, parent) VALUES (14, 'Sachsen', 'Bundesland', 0);
INSERT INTO counties (rs, county_name, type, parent) VALUES (15, 'Sachsen-Anhalt', 'Bundesland', 0);
INSERT INTO counties (rs, county_name, type, parent) VALUES (16, 'Thüringen', 'Bundesland', 0);
INSERT INTO counties (rs, county_name, type, parent) VALUES (1001, 'Flensburg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 1);
INSERT INTO counties (rs, county_name, type, parent) VALUES (1002, 'Kiel (Kreisfreie Stadt)', 'Kreisfreie Stadt', 1);
INSERT INTO counties (rs, county_name, type, parent) VALUES (1003, 'Lübeck (Kreisfreie Stadt)', 'Kreisfreie Stadt', 1);
INSERT INTO counties (rs, county_name, type, parent) VALUES (1004, 'Neumünster (Kreisfreie Stadt)', 'Kreisfreie Stadt', 1);
INSERT INTO counties (rs, county_name, type, parent) VALUES (1051, 'Dithmarschen (Kreis)', 'Kreis', 1);
INSERT INTO counties (rs, county_name, type, parent) VALUES (1053, 'Herzogtum Lauenburg (Kreis)', 'Kreis', 1);
INSERT INTO counties (rs, county_name, type, parent) VALUES (1054, 'Nordfriesland (Kreis)', 'Kreis', 1);
INSERT INTO counties (rs, county_name, type, parent) VALUES (1055, 'Ostholstein (Kreis)', 'Kreis', 1);
INSERT INTO counties (rs, county_name, type, parent) VALUES (1056, 'Pinneberg (Kreis)', 'Kreis', 1);
INSERT INTO counties (rs, county_name, type, parent) VALUES (1057, 'Plön (Kreis)', 'Kreis', 1);
INSERT INTO counties (rs, county_name, type, parent) VALUES (1058, 'Rendsburg-Eckernförde (Kreis)', 'Kreis', 1);
INSERT INTO counties (rs, county_name, type, parent) VALUES (1059, 'Schleswig-Flensburg (Kreis)', 'Kreis', 1);
INSERT INTO counties (rs, county_name, type, parent) VALUES (1060, 'Segeberg (Kreis)', 'Kreis', 1);
INSERT INTO counties (rs, county_name, type, parent) VALUES (1061, 'Steinburg (Kreis)', 'Kreis', 1);
INSERT INTO counties (rs, county_name, type, parent) VALUES (1062, 'Stormarn (Kreis)', 'Kreis', 1);
INSERT INTO counties (rs, county_name, type, parent) VALUES (2000, 'Hamburg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 2);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3101, 'Braunschweig (Kreisfreie Stadt)', 'Kreisfreie Stadt', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3102, 'Salzgitter (Kreisfreie Stadt)', 'Kreisfreie Stadt', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3103, 'Wolfsburg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3151, 'Gifhorn (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3153, 'Goslar (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3154, 'Helmstedt (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3155, 'Northeim (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3157, 'Peine (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3158, 'Wolfenbüttel (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3159, 'Göttingen (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3241, 'Hannover (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3251, 'Diepholz (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3252, 'Hameln-Pyrmont (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3254, 'Hildesheim (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3255, 'Holzminden (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3256, 'Nienburg (Weser) (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3257, 'Schaumburg (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3351, 'Celle (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3352, 'Cuxhaven (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3353, 'Harburg (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3354, 'Lüchow-Dannenberg (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3355, 'Lüneburg (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3356, 'Osterholz (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3357, 'Rotenburg (Wümme) (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3358, 'Heidekreis (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3359, 'Stade (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3360, 'Uelzen (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3361, 'Verden (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3401, 'Delmenhorst (Kreisfreie Stadt)', 'Kreisfreie Stadt', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3402, 'Emden (Kreisfreie Stadt)', 'Kreisfreie Stadt', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3403, 'Oldenburg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3404, 'Osnabrück (Kreisfreie Stadt)', 'Kreisfreie Stadt', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3405, 'Wilhelmshaven (Kreisfreie Stadt)', 'Kreisfreie Stadt', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3451, 'Ammerland (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3452, 'Aurich (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3453, 'Cloppenburg (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3454, 'Emsland (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3455, 'Friesland (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3456, 'Grafschaft Bentheim (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3457, 'Leer (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3458, 'Oldenburg (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3459, 'Osnabrück (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3460, 'Vechta (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3461, 'Wesermarsch (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (3462, 'Wittmund (Landkreis)', 'Landkreis', 3);
INSERT INTO counties (rs, county_name, type, parent) VALUES (4011, 'Bremen (Kreisfreie Stadt)', 'Kreisfreie Stadt', 4);
INSERT INTO counties (rs, county_name, type, parent) VALUES (4012, 'Bremerhaven (Kreisfreie Stadt)', 'Kreisfreie Stadt', 4);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5111, 'Düsseldorf (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5112, 'Duisburg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5113, 'Essen (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5114, 'Krefeld (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5116, 'Mönchengladbach (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5117, 'Mülheim a.d.Ruhr (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5119, 'Oberhausen (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5120, 'Remscheid (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5122, 'Solingen (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5124, 'Wuppertal (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5154, 'Kleve (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5158, 'Mettmann (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5162, 'Rhein-Kreis Neuss (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5166, 'Viersen (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5170, 'Wesel (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5314, 'Bonn (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5315, 'Köln (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5316, 'Leverkusen (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5334, 'Aachen (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5358, 'Düren (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5362, 'Rhein-Erft-Kreis (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5366, 'Euskirchen (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5370, 'Heinsberg (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5374, 'Oberbergischer Kreis (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5378, 'Rheinisch-Bergischer Kreis (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5382, 'Rhein-Sieg-Kreis (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5512, 'Bottrop (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5513, 'Gelsenkirchen (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5515, 'Münster (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5554, 'Borken (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5558, 'Coesfeld (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5562, 'Recklinghausen (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5566, 'Steinfurt (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5570, 'Warendorf (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5711, 'Bielefeld (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5754, 'Gütersloh (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5758, 'Herford (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5762, 'Höxter (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5766, 'Lippe (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5770, 'Minden-Lübbecke (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5774, 'Paderborn (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5911, 'Bochum (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5913, 'Dortmund (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5914, 'Hagen (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5915, 'Hamm (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5916, 'Herne (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5954, 'Ennepe-Ruhr-Kreis (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5958, 'Hochsauerlandkreis (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5962, 'Märkischer Kreis (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5966, 'Olpe (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5970, 'Siegen-Wittgenstein (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5974, 'Soest (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (5978, 'Unna (Kreis)', 'Kreis', 5);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6411, 'Darmstadt (Kreisfreie Stadt)', 'Kreisfreie Stadt', 6);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6412, 'Frankfurt am Main (Kreisfreie Stadt)', 'Kreisfreie Stadt', 6);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6413, 'Offenbach (Kreisfreie Stadt)', 'Kreisfreie Stadt', 6);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6414, 'Wiesbaden (Kreisfreie Stadt)', 'Kreisfreie Stadt', 6);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6431, 'Bergstraße (Landkreis)', 'Landkreis', 6);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6432, 'Darmstadt-Dieburg (Landkreis)', 'Landkreis', 6);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6433, 'Groß-Gerau (Landkreis)', 'Landkreis', 6);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6434, 'Hochtaunuskreis (Landkreis)', 'Landkreis', 6);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6435, 'Main-Kinzig-Kreis (Landkreis)', 'Landkreis', 6);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6436, 'Main-Taunus-Kreis (Landkreis)', 'Landkreis', 6);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6437, 'Odenwaldkreis (Landkreis)', 'Landkreis', 6);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6438, 'Offenbach (Landkreis)', 'Landkreis', 6);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6439, 'Rheingau-Taunus-Kreis (Landkreis)', 'Landkreis', 6);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6440, 'Wetteraukreis (Landkreis)', 'Landkreis', 6);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6531, 'Gießen (Landkreis)', 'Landkreis', 6);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6532, 'Lahn-Dill-Kreis (Landkreis)', 'Landkreis', 6);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6533, 'Limburg-Weilburg (Landkreis)', 'Landkreis', 6);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6534, 'Marburg-Biedenkopf (Landkreis)', 'Landkreis', 6);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6535, 'Vogelsbergkreis (Landkreis)', 'Landkreis', 6);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6611, 'Kassel (Kreisfreie Stadt)', 'Kreisfreie Stadt', 6);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6631, 'Fulda (Landkreis)', 'Landkreis', 6);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6632, 'Hersfeld-Rotenburg (Landkreis)', 'Landkreis', 6);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6633, 'Kassel (Landkreis)', 'Landkreis', 6);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6634, 'Schwalm-Eder-Kreis (Landkreis)', 'Landkreis', 6);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6635, 'Waldeck-Frankenberg (Landkreis)', 'Landkreis', 6);
INSERT INTO counties (rs, county_name, type, parent) VALUES (6636, 'Werra-Meißner-Kreis (Landkreis)', 'Landkreis', 6);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7111, 'Koblenz (Kreisfreie Stadt)', 'Kreisfreie Stadt', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7131, 'Ahrweiler (Landkreis)', 'Landkreis', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7132, 'Altenkirchen (Landkreis)', 'Landkreis', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7133, 'Bad Kreuznach (Landkreis)', 'Landkreis', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7134, 'Birkenfeld (Landkreis)', 'Landkreis', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7135, 'Cochem-Zell (Landkreis)', 'Landkreis', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7137, 'Mayen-Koblenz (Landkreis)', 'Landkreis', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7138, 'Neuwied (Landkreis)', 'Landkreis', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7140, 'Rhein-Hunsrück-Kreis (Landkreis)', 'Landkreis', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7141, 'Rhein-Lahn-Kreis (Landkreis)', 'Landkreis', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7143, 'Westerwaldkreis (Landkreis)', 'Landkreis', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7211, 'Trier (Kreisfreie Stadt)', 'Kreisfreie Stadt', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7231, 'Bernkastel-Wittlich (Landkreis)', 'Landkreis', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7232, 'Bitburg-Prüm (Landkreis)', 'Landkreis', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7233, 'Vulkaneifel (Landkreis)', 'Landkreis', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7235, 'Trier-Saarburg (Landkreis)', 'Landkreis', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7311, 'Frankenthal (Kreisfreie Stadt)', 'Kreisfreie Stadt', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7312, 'Kaiserslautern (Kreisfreie Stadt)', 'Kreisfreie Stadt', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7313, 'Landau i.d.Pfalz (Kreisfreie Stadt)', 'Kreisfreie Stadt', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7314, 'Ludwigshafen (Kreisfreie Stadt)', 'Kreisfreie Stadt', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7315, 'Mainz (Kreisfreie Stadt)', 'Kreisfreie Stadt', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7316, 'Neustadt a.d.Weinstraße (Kreisfreie Stadt)', 'Kreisfreie Stadt', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7317, 'Pirmasens (Kreisfreie Stadt)', 'Kreisfreie Stadt', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7318, 'Speyer (Kreisfreie Stadt)', 'Kreisfreie Stadt', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7319, 'Worms (Kreisfreie Stadt)', 'Kreisfreie Stadt', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7320, 'Zweibrücken (Kreisfreie Stadt)', 'Kreisfreie Stadt', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7331, 'Alzey-Worms (Landkreis)', 'Landkreis', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7332, 'Bad Dürkheim (Landkreis)', 'Landkreis', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7333, 'Donnersbergkreis (Landkreis)', 'Landkreis', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7334, 'Germersheim (Landkreis)', 'Landkreis', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7335, 'Kaiserslautern (Landkreis)', 'Landkreis', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7336, 'Kusel (Landkreis)', 'Landkreis', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7337, 'Südliche Weinstraße (Landkreis)', 'Landkreis', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7338, 'Rhein-Pfalz-Kreis (Landkreis)', 'Landkreis', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7339, 'Mainz-Bingen (Landkreis)', 'Landkreis', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (7340, 'Südwestpfalz (Landkreis)', 'Landkreis', 7);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8111, 'Stuttgart (Stadtkreis)', 'Stadtkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8115, 'Böblingen (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8116, 'Esslingen (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8117, 'Göppingen (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8118, 'Ludwigsburg (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8119, 'Rems-Murr-Kreis (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8121, 'Heilbronn (Stadtkreis)', 'Stadtkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8125, 'Heilbronn (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8126, 'Hohenlohekreis (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8127, 'Schwäbisch Hall (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8128, 'Main-Tauber-Kreis (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8135, 'Heidenheim (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8136, 'Ostalbkreis (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8211, 'Baden-Baden (Stadtkreis)', 'Stadtkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8212, 'Karlsruhe (Stadtkreis)', 'Stadtkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8215, 'Karlsruhe (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8216, 'Rastatt (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8221, 'Heidelberg (Stadtkreis)', 'Stadtkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8222, 'Mannheim (Stadtkreis)', 'Stadtkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8225, 'Neckar-Odenwald-Kreis (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8226, 'Rhein-Neckar-Kreis (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8231, 'Pforzheim (Stadtkreis)', 'Stadtkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8235, 'Calw (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8236, 'Enzkreis (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8237, 'Freudenstadt (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8311, 'Freiburg i.Breisgau (Stadtkreis)', 'Stadtkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8315, 'Breisgau-Hochschwarzwald (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8316, 'Emmendingen (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8317, 'Ortenaukreis (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8325, 'Rottweil (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8326, 'Schwarzwald-Baar-Kreis (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8327, 'Tuttlingen (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8335, 'Konstanz (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8336, 'Lörrach (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8337, 'Waldshut (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8415, 'Reutlingen (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8416, 'Tübingen (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8417, 'Zollernalbkreis (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8421, 'Ulm (Stadtkreis)', 'Stadtkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8425, 'Alb-Donau-Kreis (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8426, 'Biberach (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8435, 'Bodenseekreis (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8436, 'Ravensburg (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (8437, 'Sigmaringen (Landkreis)', 'Landkreis', 8);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9161, 'Ingolstadt (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9162, 'München (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9163, 'Rosenheim (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9171, 'Altötting (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9172, 'Berchtesgadener Land (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9173, 'Bad Tölz-Wolfratshausen (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9174, 'Dachau (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9175, 'Ebersberg (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9176, 'Eichstätt (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9177, 'Erding (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9178, 'Freising (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9179, 'Fürstenfeldbruck (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9180, 'Garmisch-Partenkirchen (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9181, 'Landsberg a.Lech (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9182, 'Miesbach (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9183, 'Mühldorf a.Inn (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9184, 'München (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9185, 'Neuburg-Schrobenhausen (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9186, 'Pfaffenhofen a.d.Ilm (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9187, 'Rosenheim (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9188, 'Starnberg (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9189, 'Traunstein (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9190, 'Weilheim-Schongau (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9261, 'Landshut (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9262, 'Passau (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9263, 'Straubing (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9271, 'Deggendorf (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9272, 'Freyung-Grafenau (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9273, 'Kelheim (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9274, 'Landshut (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9275, 'Passau (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9276, 'Regen (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9277, 'Rottal-Inn (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9278, 'Straubing-Bogen (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9279, 'Dingolfing-Landau (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9361, 'Amberg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9362, 'Regensburg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9363, 'Weiden i.d.OPf. (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9371, 'Amberg-Sulzbach (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9372, 'Cham (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9373, 'Neumarkt i.d.OPf. (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9374, 'Neustadt a.d.Waldnaab (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9375, 'Regensburg (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9376, 'Schwandorf (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9377, 'Tirschenreuth (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9461, 'Bamberg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9462, 'Bayreuth (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9463, 'Coburg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9464, 'Hof (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9471, 'Bamberg (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9472, 'Bayreuth (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9473, 'Coburg (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9474, 'Forchheim (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9475, 'Hof (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9476, 'Kronach (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9477, 'Kulmbach (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9478, 'Lichtenfels (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9479, 'Wunsiedel i.Fichtelgebirge (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9561, 'Ansbach (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9562, 'Erlangen (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9563, 'Fürth (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9564, 'Nürnberg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9565, 'Schwabach (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9571, 'Ansbach (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9572, 'Erlangen-Höchstadt (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9573, 'Fürth (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9574, 'Nürnberger Land (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9575, 'Neustadt a.d.Aisch-Bad Windsheim (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9576, 'Roth (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9577, 'Weißenburg-Gunzenhausen (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9661, 'Aschaffenburg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9662, 'Schweinfurt (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9663, 'Würzburg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9671, 'Aschaffenburg (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9672, 'Bad Kissingen (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9673, 'Rhön-Grabfeld (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9674, 'Haßberge (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9675, 'Kitzingen (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9676, 'Miltenberg (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9677, 'Main-Spessart (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9678, 'Schweinfurt (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9679, 'Würzburg (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9761, 'Augsburg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9762, 'Kaufbeuren (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9763, 'Kempten (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9764, 'Memmingen (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9771, 'Aichach-Friedberg (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9772, 'Augsburg (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9773, 'Dillingen a.d.Donau (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9774, 'Günzburg (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9775, 'Neu-Ulm (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9776, 'Lindau (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9777, 'Ostallgäu (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9778, 'Unterallgäu (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9779, 'Donau-Ries (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (9780, 'Oberallgäu (Landkreis)', 'Landkreis', 9);
INSERT INTO counties (rs, county_name, type, parent) VALUES (10041, 'Stadtverband Saarbrücken (Landkreis)', 'Landkreis', 10);
INSERT INTO counties (rs, county_name, type, parent) VALUES (10042, 'Merzig-Wadern (Landkreis)', 'Landkreis', 10);
INSERT INTO counties (rs, county_name, type, parent) VALUES (10043, 'Neunkirchen (Landkreis)', 'Landkreis', 10);
INSERT INTO counties (rs, county_name, type, parent) VALUES (10044, 'Saarlouis (Landkreis)', 'Landkreis', 10);
INSERT INTO counties (rs, county_name, type, parent) VALUES (10045, 'Saar-Pfalz-Kreis (Landkreis)', 'Landkreis', 10);
INSERT INTO counties (rs, county_name, type, parent) VALUES (10046, 'Sankt Wendel (Landkreis)', 'Landkreis', 10);
INSERT INTO counties (rs, county_name, type, parent) VALUES (11001, 'Berlin Mitte (Bezirk)', 'Bezirk', 11);
INSERT INTO counties (rs, county_name, type, parent) VALUES (11002, 'Berlin Friedrichshain-Kreuzberg (Bezirk)', 'Bezirk', 11);
INSERT INTO counties (rs, county_name, type, parent) VALUES (11003, 'Berlin Pankow (Bezirk)', 'Bezirk', 11);
INSERT INTO counties (rs, county_name, type, parent) VALUES (11004, 'Berlin Charlottenburg-Wilmersdorf (Bezirk)', 'Bezirk', 11);
INSERT INTO counties (rs, county_name, type, parent) VALUES (11005, 'Berlin Spandau (Bezirk)', 'Bezirk', 11);
INSERT INTO counties (rs, county_name, type, parent) VALUES (11006, 'Berlin Steglitz-Zehlendorf (Bezirk)', 'Bezirk', 11);
INSERT INTO counties (rs, county_name, type, parent) VALUES (11007, 'Berlin Tempelhof-Schöneberg (Bezirk)', 'Bezirk', 11);
INSERT INTO counties (rs, county_name, type, parent) VALUES (11008, 'Berlin Neukölln (Bezirk)', 'Bezirk', 11);
INSERT INTO counties (rs, county_name, type, parent) VALUES (11009, 'Berlin Treptow-Köpenick (Bezirk)', 'Bezirk', 11);
INSERT INTO counties (rs, county_name, type, parent) VALUES (11010, 'Berlin Marzahn-Hellersdorf (Bezirk)', 'Bezirk', 11);
INSERT INTO counties (rs, county_name, type, parent) VALUES (11011, 'Berlin Lichtenberg (Bezirk)', 'Bezirk', 11);
INSERT INTO counties (rs, county_name, type, parent) VALUES (11012, 'Berlin Reinickendorf (Bezirk)', 'Bezirk', 11);
INSERT INTO counties (rs, county_name, type, parent) VALUES (12051, 'Brandenburg a.d.Havel (Kreisfreie Stadt)', 'Kreisfreie Stadt', 12);
INSERT INTO counties (rs, county_name, type, parent) VALUES (12052, 'Cottbus (Kreisfreie Stadt)', 'Kreisfreie Stadt', 12);
INSERT INTO counties (rs, county_name, type, parent) VALUES (12053, 'Frankfurt (Oder) (Kreisfreie Stadt)', 'Kreisfreie Stadt', 12);
INSERT INTO counties (rs, county_name, type, parent) VALUES (12054, 'Potsdam (Kreisfreie Stadt)', 'Kreisfreie Stadt', 12);
INSERT INTO counties (rs, county_name, type, parent) VALUES (12060, 'Barnim (Landkreis)', 'Landkreis', 12);
INSERT INTO counties (rs, county_name, type, parent) VALUES (12061, 'Dahme-Spreewald (Landkreis)', 'Landkreis', 12);
INSERT INTO counties (rs, county_name, type, parent) VALUES (12062, 'Elbe-Elster (Landkreis)', 'Landkreis', 12);
INSERT INTO counties (rs, county_name, type, parent) VALUES (12063, 'Havelland (Landkreis)', 'Landkreis', 12);
INSERT INTO counties (rs, county_name, type, parent) VALUES (12064, 'Märkisch-Oderland (Landkreis)', 'Landkreis', 12);
INSERT INTO counties (rs, county_name, type, parent) VALUES (12065, 'Oberhavel (Landkreis)', 'Landkreis', 12);
INSERT INTO counties (rs, county_name, type, parent) VALUES (12066, 'Oberspreewald-Lausitz (Landkreis)', 'Landkreis', 12);
INSERT INTO counties (rs, county_name, type, parent) VALUES (12067, 'Oder-Spree (Landkreis)', 'Landkreis', 12);
INSERT INTO counties (rs, county_name, type, parent) VALUES (12068, 'Ostprignitz-Ruppin (Landkreis)', 'Landkreis', 12);
INSERT INTO counties (rs, county_name, type, parent) VALUES (12069, 'Potsdam-Mittelmark (Landkreis)', 'Landkreis', 12);
INSERT INTO counties (rs, county_name, type, parent) VALUES (12070, 'Prignitz (Landkreis)', 'Landkreis', 12);
INSERT INTO counties (rs, county_name, type, parent) VALUES (12071, 'Spree-Neiße (Landkreis)', 'Landkreis', 12);
INSERT INTO counties (rs, county_name, type, parent) VALUES (12072, 'Teltow-Fläming (Landkreis)', 'Landkreis', 12);
INSERT INTO counties (rs, county_name, type, parent) VALUES (12073, 'Uckermark (Landkreis)', 'Landkreis', 12);
INSERT INTO counties (rs, county_name, type, parent) VALUES (13003, 'Rostock (Kreisfreie Stadt)', 'Kreisfreie Stadt', 13);
INSERT INTO counties (rs, county_name, type, parent) VALUES (13004, 'Schwerin (Kreisfreie Stadt)', 'Kreisfreie Stadt', 13);
INSERT INTO counties (rs, county_name, type, parent) VALUES (13071, 'Mecklenburgische Seenplatte (Landkreis)', 'Landkreis', 13);
INSERT INTO counties (rs, county_name, type, parent) VALUES (13072, 'Rostock (Landkreis)', 'Landkreis', 13);
INSERT INTO counties (rs, county_name, type, parent) VALUES (13073, 'Vorpommern-Rügen (Landkreis)', 'Landkreis', 13);
INSERT INTO counties (rs, county_name, type, parent) VALUES (13074, 'Nordwestmecklenburg (Landkreis)', 'Landkreis', 13);
INSERT INTO counties (rs, county_name, type, parent) VALUES (13075, 'Vorpommern-Greifswald (Landkreis)', 'Landkreis', 13);
INSERT INTO counties (rs, county_name, type, parent) VALUES (13076, 'Ludwigslust-Parchim (Landkreis)', 'Landkreis', 13);
INSERT INTO counties (rs, county_name, type, parent) VALUES (14511, 'Chemnitz (Kreisfreie Stadt)', 'Kreisfreie Stadt', 14);
INSERT INTO counties (rs, county_name, type, parent) VALUES (14521, 'Erzgebirgskreis (Landkreis)', 'Landkreis', 14);
INSERT INTO counties (rs, county_name, type, parent) VALUES (14522, 'Mittelsachsen (Landkreis)', 'Landkreis', 14);
INSERT INTO counties (rs, county_name, type, parent) VALUES (14523, 'Vogtlandkreis (Landkreis)', 'Landkreis', 14);
INSERT INTO counties (rs, county_name, type, parent) VALUES (14524, 'Zwickau (Landkreis)', 'Landkreis', 14);
INSERT INTO counties (rs, county_name, type, parent) VALUES (14612, 'Dresden (Kreisfreie Stadt)', 'Kreisfreie Stadt', 14);
INSERT INTO counties (rs, county_name, type, parent) VALUES (14625, 'Bautzen (Landkreis)', 'Landkreis', 14);
INSERT INTO counties (rs, county_name, type, parent) VALUES (14626, 'Görlitz (Landkreis)', 'Landkreis', 14);
INSERT INTO counties (rs, county_name, type, parent) VALUES (14627, 'Meißen (Landkreis)', 'Landkreis', 14);
INSERT INTO counties (rs, county_name, type, parent) VALUES (14628, 'Sächsische Schweiz-Osterzgebirge (Landkreis)', 'Landkreis', 14);
INSERT INTO counties (rs, county_name, type, parent) VALUES (14713, 'Leipzig (Kreisfreie Stadt)', 'Kreisfreie Stadt', 14);
INSERT INTO counties (rs, county_name, type, parent) VALUES (14729, 'Leipzig (Landkreis)', 'Landkreis', 14);
INSERT INTO counties (rs, county_name, type, parent) VALUES (14730, 'Nordsachsen (Landkreis)', 'Landkreis', 14);
INSERT INTO counties (rs, county_name, type, parent) VALUES (15001, 'Dessau-Roßlau (Kreisfreie Stadt)', 'Kreisfreie Stadt', 15);
INSERT INTO counties (rs, county_name, type, parent) VALUES (15002, 'Halle (Kreisfreie Stadt)', 'Kreisfreie Stadt', 15);
INSERT INTO counties (rs, county_name, type, parent) VALUES (15003, 'Magdeburg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 15);
INSERT INTO counties (rs, county_name, type, parent) VALUES (15081, 'Altmarkkreis Salzwedel (Landkreis)', 'Landkreis', 15);
INSERT INTO counties (rs, county_name, type, parent) VALUES (15082, 'Anhalt-Bitterfeld (Landkreis)', 'Landkreis', 15);
INSERT INTO counties (rs, county_name, type, parent) VALUES (15083, 'Börde (Landkreis)', 'Landkreis', 15);
INSERT INTO counties (rs, county_name, type, parent) VALUES (15084, 'Burgenlandkreis (Landkreis)', 'Landkreis', 15);
INSERT INTO counties (rs, county_name, type, parent) VALUES (15085, 'Harz (Landkreis)', 'Landkreis', 15);
INSERT INTO counties (rs, county_name, type, parent) VALUES (15086, 'Jerichower Land (Landkreis)', 'Landkreis', 15);
INSERT INTO counties (rs, county_name, type, parent) VALUES (15087, 'Mansfeld-Südharz (Landkreis)', 'Landkreis', 15);
INSERT INTO counties (rs, county_name, type, parent) VALUES (15088, 'Saalekreis (Landkreis)', 'Landkreis', 15);
INSERT INTO counties (rs, county_name, type, parent) VALUES (15089, 'Salzlandkreis (Landkreis)', 'Landkreis', 15);
INSERT INTO counties (rs, county_name, type, parent) VALUES (15090, 'Stendal (Landkreis)', 'Landkreis', 15);
INSERT INTO counties (rs, county_name, type, parent) VALUES (15091, 'Wittenberg (Landkreis)', 'Landkreis', 15);
INSERT INTO counties (rs, county_name, type, parent) VALUES (16051, 'Erfurt (Kreisfreie Stadt)', 'Kreisfreie Stadt', 16);
INSERT INTO counties (rs, county_name, type, parent) VALUES (16052, 'Gera (Kreisfreie Stadt)', 'Kreisfreie Stadt', 16);
INSERT INTO counties (rs, county_name, type, parent) VALUES (16053, 'Jena (Kreisfreie Stadt)', 'Kreisfreie Stadt', 16);
INSERT INTO counties (rs, county_name, type, parent) VALUES (16054, 'Suhl (Kreisfreie Stadt)', 'Kreisfreie Stadt', 16);
INSERT INTO counties (rs, county_name, type, parent) VALUES (16055, 'Weimar (Kreisfreie Stadt)', 'Kreisfreie Stadt', 16);
INSERT INTO counties (rs, county_name, type, parent) VALUES (16056, 'Eisenach (Kreisfreie Stadt)', 'Kreisfreie Stadt', 16);
INSERT INTO counties (rs, county_name, type, parent) VALUES (16061, 'Eichsfeld (Landkreis)', 'Landkreis', 16);
INSERT INTO counties (rs, county_name, type, parent) VALUES (16062, 'Nordhausen (Landkreis)', 'Landkreis', 16);
INSERT INTO counties (rs, county_name, type, parent) VALUES (16063, 'Wartburgkreis (Landkreis)', 'Landkreis', 16);
INSERT INTO counties (rs, county_name, type, parent) VALUES (16064, 'Unstrut-Hainich-Kreis (Landkreis)', 'Landkreis', 16);
INSERT INTO counties (rs, county_name, type, parent) VALUES (16065, 'Kyffhäuserkreis (Landkreis)', 'Landkreis', 16);
INSERT INTO counties (rs, county_name, type, parent) VALUES (16066, 'Schmalkalden-Meiningen (Landkreis)', 'Landkreis', 16);
INSERT INTO counties (rs, county_name, type, parent) VALUES (16067, 'Gotha (Landkreis)', 'Landkreis', 16);
INSERT INTO counties (rs, county_name, type, parent) VALUES (16068, 'Sömmerda (Landkreis)', 'Landkreis', 16);
INSERT INTO counties (rs, county_name, type, parent) VALUES (16069, 'Hildburghausen (Landkreis)', 'Landkreis', 16);
INSERT INTO counties (rs, county_name, type, parent) VALUES (16070, 'Ilm-Kreis (Landkreis)', 'Landkreis', 16);
INSERT INTO counties (rs, county_name, type, parent) VALUES (16071, 'Weimarer Land (Landkreis)', 'Landkreis', 16);
INSERT INTO counties (rs, county_name, type, parent) VALUES (16072, 'Sonneberg (Landkreis)', 'Landkreis', 16);
INSERT INTO counties (rs, county_name, type, parent) VALUES (16073, 'Saalfeld-Rudolstadt (Landkreis)', 'Landkreis', 16);
INSERT INTO counties (rs, county_name, type, parent) VALUES (16074, 'Saale-Holzland-Kreis (Landkreis)', 'Landkreis', 16);
INSERT INTO counties (rs, county_name, type, parent) VALUES (16075, 'Saale-Orla-Kreis (Landkreis)', 'Landkreis', 16);
INSERT INTO counties (rs, county_name, type, parent) VALUES (16076, 'Greiz (Landkreis)', 'Landkreis', 16);
INSERT INTO counties (rs, county_name, type, parent) VALUES (16077, 'Altenburger Land (Landkreis)', 'Landkreis', 16);