INSERT INTO counties (rs, county_name, type, parent, population) VALUES (0, 'Bundesrepublik Deutschland', 'Staat', null, null);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (1, 'Schleswig-Holstein', 'Bundesland', 0, null);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (2, 'Hamburg', 'Bundesland', 0, null);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3, 'Niedersachsen', 'Bundesland', 0, null);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (4, 'Bremen', 'Bundesland', 0, null);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5, 'Nordrhein-Westfalen', 'Bundesland', 0, null);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6, 'Hessen', 'Bundesland', 0, null);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7, 'Rheinland-Pfalz', 'Bundesland', 0, null);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8, 'Baden-Württemberg', 'Bundesland', 0, null);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9, 'Bayern', 'Bundesland', 0, null);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (10, 'Saarland', 'Bundesland', 0, null);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (11, 'Berlin', 'Bundesland', 0, null);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (12, 'Brandenburg', 'Bundesland', 0, null);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (13, 'Mecklenburg-Vorpommern', 'Bundesland', 0, null);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (14, 'Sachsen', 'Bundesland', 0, null);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (15, 'Sachsen-Anhalt', 'Bundesland', 0, null);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (16, 'Thüringen', 'Bundesland', 0, null);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (1001, 'Flensburg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 1, 90164);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (1002, 'Kiel (Kreisfreie Stadt)', 'Kreisfreie Stadt', 1, 246794);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (1003, 'Lübeck (Kreisfreie Stadt)', 'Kreisfreie Stadt', 1, 216530);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (1004, 'Neumünster (Kreisfreie Stadt)', 'Kreisfreie Stadt', 1, 80196);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (1051, 'Dithmarschen (Kreis)', 'Kreis', 1, 133193);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (1053, 'Herzogtum Lauenburg (Kreis)', 'Kreis', 1, 198019);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (1054, 'Nordfriesland (Kreis)', 'Kreis', 1, 165951);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (1055, 'Ostholstein (Kreis)', 'Kreis', 1, 200539);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (1056, 'Pinneberg (Kreis)', 'Kreis', 1, 316103);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (1057, 'Plön (Kreis)', 'Kreis', 1, 128686);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (1058, 'Rendsburg-Eckernförde (Kreis)', 'Kreis', 1, 274098);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (1059, 'Schleswig-Flensburg (Kreis)', 'Kreis', 1, 201156);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (1060, 'Segeberg (Kreis)', 'Kreis', 1, 277175);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (1061, 'Steinburg (Kreis)', 'Kreis', 1, 131013);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (1062, 'Stormarn (Kreis)', 'Kreis', 1, 244156);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (2000, 'Hamburg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 2, 1847253);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3101, 'Braunschweig (Kreisfreie Stadt)', 'Kreisfreie Stadt', 3, 249406);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3102, 'Salzgitter (Kreisfreie Stadt)', 'Kreisfreie Stadt', 3, 104291);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3103, 'Wolfsburg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 3, 124371);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3151, 'Gifhorn (Landkreis)', 'Landkreis', 3, 176523);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3153, 'Goslar (Landkreis)', 'Landkreis', 3, 136292);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3154, 'Helmstedt (Landkreis)', 'Landkreis', 3, 91297);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3155, 'Northeim (Landkreis)', 'Landkreis', 3, 132285);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3157, 'Peine (Landkreis)', 'Landkreis', 3, 134801);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3158, 'Wolfenbüttel (Landkreis)', 'Landkreis', 3, 119622);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3159, 'Göttingen (Landkreis)', 'Landkreis', 3, 326041);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3241, 'Hannover (Landkreis)', 'Landkreis', 3, 1157115);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3251, 'Diepholz (Landkreis)', 'Landkreis', 3, 217089);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3252, 'Hameln-Pyrmont (Landkreis)', 'Landkreis', 3, 148549);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3254, 'Hildesheim (Landkreis)', 'Landkreis', 3, 275817);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3255, 'Holzminden (Landkreis)', 'Landkreis', 3, 70458);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3256, 'Nienburg (Weser) (Landkreis)', 'Landkreis', 3, 121390);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3257, 'Schaumburg (Landkreis)', 'Landkreis', 3, 157820);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3351, 'Celle (Landkreis)', 'Landkreis', 3, 179011);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3352, 'Cuxhaven (Landkreis)', 'Landkreis', 3, 198038);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3353, 'Harburg (Landkreis)', 'Landkreis', 3, 254431);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3354, 'Lüchow-Dannenberg (Landkreis)', 'Landkreis', 3, 48412);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3355, 'Lüneburg (Landkreis)', 'Landkreis', 3, 184139);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3356, 'Osterholz (Landkreis)', 'Landkreis', 3, 113928);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3357, 'Rotenburg (Wümme) (Landkreis)', 'Landkreis', 3, 163782);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3358, 'Heidekreis (Landkreis)', 'Landkreis', 3, 140673);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3359, 'Stade (Landkreis)', 'Landkreis', 3, 204512);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3360, 'Uelzen (Landkreis)', 'Landkreis', 3, 92389);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3361, 'Verden (Landkreis)', 'Landkreis', 3, 137133);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3401, 'Delmenhorst (Kreisfreie Stadt)', 'Kreisfreie Stadt', 3, 77559);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3402, 'Emden (Kreisfreie Stadt)', 'Kreisfreie Stadt', 3, 49913);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3403, 'Oldenburg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 3, 169077);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3404, 'Osnabrück (Kreisfreie Stadt)', 'Kreisfreie Stadt', 3, 165251);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3405, 'Wilhelmshaven (Kreisfreie Stadt)', 'Kreisfreie Stadt', 3, 76089);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3451, 'Ammerland (Landkreis)', 'Landkreis', 3, 124859);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3452, 'Aurich (Landkreis)', 'Landkreis', 3, 189694);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3453, 'Cloppenburg (Landkreis)', 'Landkreis', 3, 170682);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3454, 'Emsland (Landkreis)', 'Landkreis', 3, 326954);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3455, 'Friesland (Landkreis)', 'Landkreis', 3, 98704);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3456, 'Grafschaft Bentheim (Landkreis)', 'Landkreis', 3, 137162);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3457, 'Leer (Landkreis)', 'Landkreis', 3, 170756);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3458, 'Oldenburg (Landkreis)', 'Landkreis', 3, 130890);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3459, 'Osnabrück (Landkreis)', 'Landkreis', 3, 358080);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3460, 'Vechta (Landkreis)', 'Landkreis', 3, 142814);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3461, 'Wesermarsch (Landkreis)', 'Landkreis', 3, 88583);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (3462, 'Wittmund (Landkreis)', 'Landkreis', 3, 56926);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (4011, 'Bremen (Kreisfreie Stadt)', 'Kreisfreie Stadt', 4, 567559);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (4012, 'Bremerhaven (Kreisfreie Stadt)', 'Kreisfreie Stadt', 4, 113643);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5111, 'Düsseldorf (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5, 621877);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5112, 'Duisburg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5, 498686);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5113, 'Essen (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5, 582760);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5114, 'Krefeld (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5, 227417);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5116, 'Mönchengladbach (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5, 261034);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5117, 'Mülheim a.d.Ruhr (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5, 170632);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5119, 'Oberhausen (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5, 210764);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5120, 'Remscheid (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5, 111338);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5122, 'Solingen (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5, 159245);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5124, 'Wuppertal (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5, 355100);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5154, 'Kleve (Kreis)', 'Kreis', 5, 312465);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5158, 'Mettmann (Kreis)', 'Kreis', 5, 485570);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5162, 'Rhein-Kreis Neuss (Kreis)', 'Kreis', 5, 451730);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5166, 'Viersen (Kreis)', 'Kreis', 5, 298863);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5170, 'Wesel (Kreis)', 'Kreis', 5, 459976);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5314, 'Bonn (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5, 329673);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5315, 'Köln (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5, 1087863);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5316, 'Leverkusen (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5, 163729);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5334, 'Aachen (Kreis)', 'Kreis', 5, 557026);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5358, 'Düren (Kreis)', 'Kreis', 5, 264638);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5362, 'Rhein-Erft-Kreis (Kreis)', 'Kreis', 5, 470615);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5366, 'Euskirchen (Kreis)', 'Kreis', 5, 193656);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5370, 'Heinsberg (Kreis)', 'Kreis', 5, 255555);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5374, 'Oberbergischer Kreis (Kreis)', 'Kreis', 5, 272057);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5378, 'Rheinisch-Bergischer Kreis (Kreis)', 'Kreis', 5, 283271);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5382, 'Rhein-Sieg-Kreis (Kreis)', 'Kreis', 5, 600764);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5512, 'Bottrop (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5, 117565);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5513, 'Gelsenkirchen (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5, 259645);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5515, 'Münster (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5, 315293);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5554, 'Borken (Kreis)', 'Kreis', 5, 371339);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5558, 'Coesfeld (Kreis)', 'Kreis', 5, 220586);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5562, 'Recklinghausen (Kreis)', 'Kreis', 5, 614137);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5566, 'Steinfurt (Kreis)', 'Kreis', 5, 448220);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5570, 'Warendorf (Kreis)', 'Kreis', 5, 277840);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5711, 'Bielefeld (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5, 334195);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5754, 'Gütersloh (Kreis)', 'Kreis', 5, 364938);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5758, 'Herford (Kreis)', 'Kreis', 5, 250578);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5762, 'Höxter (Kreis)', 'Kreis', 5, 140251);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5766, 'Lippe (Kreis)', 'Kreis', 5, 347514);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5770, 'Minden-Lübbecke (Kreis)', 'Kreis', 5, 310409);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5774, 'Paderborn (Kreis)', 'Kreis', 5, 307839);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5911, 'Bochum (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5, 365587);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5913, 'Dortmund (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5, 588250);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5914, 'Hagen (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5, 188686);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5915, 'Hamm (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5, 179916);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5916, 'Herne (Kreisfreie Stadt)', 'Kreisfreie Stadt', 5, 156449);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5954, 'Ennepe-Ruhr-Kreis (Kreis)', 'Kreis', 5, 324106);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5958, 'Hochsauerlandkreis (Kreis)', 'Kreis', 5, 259777);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5962, 'Märkischer Kreis (Kreis)', 'Kreis', 5, 410222);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5966, 'Olpe (Kreis)', 'Kreis', 5, 133955);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5970, 'Siegen-Wittgenstein (Kreis)', 'Kreis', 5, 276944);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5974, 'Soest (Kreis)', 'Kreis', 5, 301785);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (5978, 'Unna (Kreis)', 'Kreis', 5, 394891);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6411, 'Darmstadt (Kreisfreie Stadt)', 'Kreisfreie Stadt', 6, 159878);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6412, 'Frankfurt am Main (Kreisfreie Stadt)', 'Kreisfreie Stadt', 6, 763380);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6413, 'Offenbach (Kreisfreie Stadt)', 'Kreisfreie Stadt', 6, 130280);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6414, 'Wiesbaden (Kreisfreie Stadt)', 'Kreisfreie Stadt', 6, 278474);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6431, 'Bergstraße (Landkreis)', 'Landkreis', 6, 270340);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6432, 'Darmstadt-Dieburg (Landkreis)', 'Landkreis', 6, 297844);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6433, 'Groß-Gerau (Landkreis)', 'Landkreis', 6, 275726);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6434, 'Hochtaunuskreis (Landkreis)', 'Landkreis', 6, 236914);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6435, 'Main-Kinzig-Kreis (Landkreis)', 'Landkreis', 6, 420552);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6436, 'Main-Taunus-Kreis (Landkreis)', 'Landkreis', 6, 238558);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6437, 'Odenwaldkreis (Landkreis)', 'Landkreis', 6, 96703);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6438, 'Offenbach (Landkreis)', 'Landkreis', 6, 355813);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6439, 'Rheingau-Taunus-Kreis (Landkreis)', 'Landkreis', 6, 187160);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6440, 'Wetteraukreis (Landkreis)', 'Landkreis', 6, 308339);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6531, 'Gießen (Landkreis)', 'Landkreis', 6, 270688);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6532, 'Lahn-Dill-Kreis (Landkreis)', 'Landkreis', 6, 253319);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6533, 'Limburg-Weilburg (Landkreis)', 'Landkreis', 6, 171912);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6534, 'Marburg-Biedenkopf (Landkreis)', 'Landkreis', 6, 247084);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6535, 'Vogelsbergkreis (Landkreis)', 'Landkreis', 6, 105643);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6611, 'Kassel (Kreisfreie Stadt)', 'Kreisfreie Stadt', 6, 202137);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6631, 'Fulda (Landkreis)', 'Landkreis', 6, 223145);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6632, 'Hersfeld-Rotenburg (Landkreis)', 'Landkreis', 6, 120719);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6633, 'Kassel (Landkreis)', 'Landkreis', 6, 236764);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6634, 'Schwalm-Eder-Kreis (Landkreis)', 'Landkreis', 6, 179673);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6635, 'Waldeck-Frankenberg (Landkreis)', 'Landkreis', 6, 156406);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (6636, 'Werra-Meißner-Kreis (Landkreis)', 'Landkreis', 6, 100629);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7111, 'Koblenz (Kreisfreie Stadt)', 'Kreisfreie Stadt', 7, 114052);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7131, 'Ahrweiler (Landkreis)', 'Landkreis', 7, 130086);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7132, 'Altenkirchen (Landkreis)', 'Landkreis', 7, 128805);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7133, 'Bad Kreuznach (Landkreis)', 'Landkreis', 7, 158345);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7134, 'Birkenfeld (Landkreis)', 'Landkreis', 7, 80951);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7135, 'Cochem-Zell (Landkreis)', 'Landkreis', 7, 61375);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7137, 'Mayen-Koblenz (Landkreis)', 'Landkreis', 7, 214434);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7138, 'Neuwied (Landkreis)', 'Landkreis', 7, 182811);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7140, 'Rhein-Hunsrück-Kreis (Landkreis)', 'Landkreis', 7, 103163);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7141, 'Rhein-Lahn-Kreis (Landkreis)', 'Landkreis', 7, 122297);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7143, 'Westerwaldkreis (Landkreis)', 'Landkreis', 7, 201904);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7211, 'Trier (Kreisfreie Stadt)', 'Kreisfreie Stadt', 7, 111528);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7231, 'Bernkastel-Wittlich (Landkreis)', 'Landkreis', 7, 112483);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7232, 'Bitburg-Prüm (Landkreis)', 'Landkreis', 7, 99058);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7233, 'Vulkaneifel (Landkreis)', 'Landkreis', 7, 60646);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7235, 'Trier-Saarburg (Landkreis)', 'Landkreis', 7, 149398);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7311, 'Frankenthal (Kreisfreie Stadt)', 'Kreisfreie Stadt', 7, 48762);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7312, 'Kaiserslautern (Kreisfreie Stadt)', 'Kreisfreie Stadt', 7, 100030);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7313, 'Landau i.d.Pfalz (Kreisfreie Stadt)', 'Kreisfreie Stadt', 7, 46881);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7314, 'Ludwigshafen (Kreisfreie Stadt)', 'Kreisfreie Stadt', 7, 172253);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7315, 'Mainz (Kreisfreie Stadt)', 'Kreisfreie Stadt', 7, 218578);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7316, 'Neustadt a.d.Weinstraße (Kreisfreie Stadt)', 'Kreisfreie Stadt', 7, 53264);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7317, 'Pirmasens (Kreisfreie Stadt)', 'Kreisfreie Stadt', 7, 40231);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7318, 'Speyer (Kreisfreie Stadt)', 'Kreisfreie Stadt', 7, 50561);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7319, 'Worms (Kreisfreie Stadt)', 'Kreisfreie Stadt', 7, 83542);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7320, 'Zweibrücken (Kreisfreie Stadt)', 'Kreisfreie Stadt', 7, 34193);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7331, 'Alzey-Worms (Landkreis)', 'Landkreis', 7, 129687);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7332, 'Bad Dürkheim (Landkreis)', 'Landkreis', 7, 132671);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7333, 'Donnersbergkreis (Landkreis)', 'Landkreis', 7, 75325);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7334, 'Germersheim (Landkreis)', 'Landkreis', 7, 129013);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7335, 'Kaiserslautern (Landkreis)', 'Landkreis', 7, 105979);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7336, 'Kusel (Landkreis)', 'Landkreis', 7, 70219);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7337, 'Südliche Weinstraße (Landkreis)', 'Landkreis', 7, 110521);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7338, 'Rhein-Pfalz-Kreis (Landkreis)', 'Landkreis', 7, 154609);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7339, 'Mainz-Bingen (Landkreis)', 'Landkreis', 7, 211417);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (7340, 'Südwestpfalz (Landkreis)', 'Landkreis', 7, 94831);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8111, 'Stuttgart (Stadtkreis)', 'Stadtkreis', 8, 635911);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8115, 'Böblingen (Landkreis)', 'Landkreis', 8, 392807);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8116, 'Esslingen (Landkreis)', 'Landkreis', 8, 535024);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8117, 'Göppingen (Landkreis)', 'Landkreis', 8, 258145);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8118, 'Ludwigsburg (Landkreis)', 'Landkreis', 8, 545423);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8119, 'Rems-Murr-Kreis (Landkreis)', 'Landkreis', 8, 427248);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8121, 'Heilbronn (Stadtkreis)', 'Stadtkreis', 8, 126592);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8125, 'Heilbronn (Landkreis)', 'Landkreis', 8, 344456);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8126, 'Hohenlohekreis (Landkreis)', 'Landkreis', 8, 112655);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8127, 'Schwäbisch Hall (Landkreis)', 'Landkreis', 8, 196761);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8128, 'Main-Tauber-Kreis (Landkreis)', 'Landkreis', 8, 132399);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8135, 'Heidenheim (Landkreis)', 'Landkreis', 8, 132777);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8136, 'Ostalbkreis (Landkreis)', 'Landkreis', 8, 314025);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8211, 'Baden-Baden (Stadtkreis)', 'Stadtkreis', 8, 55185);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8212, 'Karlsruhe (Stadtkreis)', 'Stadtkreis', 8, 312060);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8215, 'Karlsruhe (Landkreis)', 'Landkreis', 8, 445101);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8216, 'Rastatt (Landkreis)', 'Landkreis', 8, 231420);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8221, 'Heidelberg (Stadtkreis)', 'Stadtkreis', 8, 161485);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8222, 'Mannheim (Stadtkreis)', 'Stadtkreis', 8, 310658);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8225, 'Neckar-Odenwald-Kreis (Landkreis)', 'Landkreis', 8, 143633);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8226, 'Rhein-Neckar-Kreis (Landkreis)', 'Landkreis', 8, 548355);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8231, 'Pforzheim (Stadtkreis)', 'Stadtkreis', 8, 125957);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8235, 'Calw (Landkreis)', 'Landkreis', 8, 159201);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8236, 'Enzkreis (Landkreis)', 'Landkreis', 8, 199556);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8237, 'Freudenstadt (Landkreis)', 'Landkreis', 8, 118243);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8311, 'Freiburg i.Breisgau (Stadtkreis)', 'Stadtkreis', 8, 231195);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8315, 'Breisgau-Hochschwarzwald (Landkreis)', 'Landkreis', 8, 263601);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8316, 'Emmendingen (Landkreis)', 'Landkreis', 8, 166408);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8317, 'Ortenaukreis (Landkreis)', 'Landkreis', 8, 430953);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8325, 'Rottweil (Landkreis)', 'Landkreis', 8, 139878);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8326, 'Schwarzwald-Baar-Kreis (Landkreis)', 'Landkreis', 8, 212506);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8327, 'Tuttlingen (Landkreis)', 'Landkreis', 8, 140766);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8335, 'Konstanz (Landkreis)', 'Landkreis', 8, 286305);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8336, 'Lörrach (Landkreis)', 'Landkreis', 8, 228736);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8337, 'Waldshut (Landkreis)', 'Landkreis', 8, 171003);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8415, 'Reutlingen (Landkreis)', 'Landkreis', 8, 287034);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8416, 'Tübingen (Landkreis)', 'Landkreis', 8, 228678);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8417, 'Zollernalbkreis (Landkreis)', 'Landkreis', 8, 189363);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8421, 'Ulm (Stadtkreis)', 'Stadtkreis', 8, 126790);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8425, 'Alb-Donau-Kreis (Landkreis)', 'Landkreis', 8, 197076);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8426, 'Biberach (Landkreis)', 'Landkreis', 8, 201282);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8435, 'Bodenseekreis (Landkreis)', 'Landkreis', 8, 217470);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8436, 'Ravensburg (Landkreis)', 'Landkreis', 8, 285424);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (8437, 'Sigmaringen (Landkreis)', 'Landkreis', 8, 130849);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9161, 'Ingolstadt (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9, 137392);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9162, 'München (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9, 1484226);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9163, 'Rosenheim (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9, 63551);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9171, 'Altötting (Landkreis)', 'Landkreis', 9, 111516);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9172, 'Berchtesgadener Land (Landkreis)', 'Landkreis', 9, 105929);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9173, 'Bad Tölz-Wolfratshausen (Landkreis)', 'Landkreis', 9, 127917);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9174, 'Dachau (Landkreis)', 'Landkreis', 9, 154899);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9175, 'Ebersberg (Landkreis)', 'Landkreis', 9, 143649);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9176, 'Eichstätt (Landkreis)', 'Landkreis', 9, 132881);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9177, 'Erding (Landkreis)', 'Landkreis', 9, 138182);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9178, 'Freising (Landkreis)', 'Landkreis', 9, 180007);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9179, 'Fürstenfeldbruck (Landkreis)', 'Landkreis', 9, 219311);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9180, 'Garmisch-Partenkirchen (Landkreis)', 'Landkreis', 9, 88424);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9181, 'Landsberg a.Lech (Landkreis)', 'Landkreis', 9, 120302);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9182, 'Miesbach (Landkreis)', 'Landkreis', 9, 100010);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9183, 'Mühldorf a.Inn (Landkreis)', 'Landkreis', 9, 115872);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9184, 'München (Landkreis)', 'Landkreis', 9, 350473);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9185, 'Neuburg-Schrobenhausen (Landkreis)', 'Landkreis', 9, 97303);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9186, 'Pfaffenhofen a.d.Ilm (Landkreis)', 'Landkreis', 9, 128227);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9187, 'Rosenheim (Landkreis)', 'Landkreis', 9, 261330);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9188, 'Starnberg (Landkreis)', 'Landkreis', 9, 136667);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9189, 'Traunstein (Landkreis)', 'Landkreis', 9, 177319);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9190, 'Weilheim-Schongau (Landkreis)', 'Landkreis', 9, 135478);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9261, 'Landshut (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9, 73411);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9262, 'Passau (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9, 52803);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9263, 'Straubing (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9, 47791);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9271, 'Deggendorf (Landkreis)', 'Landkreis', 9, 119478);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9272, 'Freyung-Grafenau (Landkreis)', 'Landkreis', 9, 78362);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9273, 'Kelheim (Landkreis)', 'Landkreis', 9, 123058);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9274, 'Landshut (Landkreis)', 'Landkreis', 9, 159895);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9275, 'Passau (Landkreis)', 'Landkreis', 9, 192656);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9276, 'Regen (Landkreis)', 'Landkreis', 9, 77410);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9277, 'Rottal-Inn (Landkreis)', 'Landkreis', 9, 121502);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9278, 'Straubing-Bogen (Landkreis)', 'Landkreis', 9, 101120);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9279, 'Dingolfing-Landau (Landkreis)', 'Landkreis', 9, 96683);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9361, 'Amberg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9, 42207);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9362, 'Regensburg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9, 153094);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9363, 'Weiden i.d.OPf. (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9, 42743);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9371, 'Amberg-Sulzbach (Landkreis)', 'Landkreis', 9, 103049);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9372, 'Cham (Landkreis)', 'Landkreis', 9, 127998);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9373, 'Neumarkt i.d.OPf. (Landkreis)', 'Landkreis', 9, 134573);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9374, 'Neustadt a.d.Waldnaab (Landkreis)', 'Landkreis', 9, 94450);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9375, 'Regensburg (Landkreis)', 'Landkreis', 9, 194070);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9376, 'Schwandorf (Landkreis)', 'Landkreis', 9, 147872);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9377, 'Tirschenreuth (Landkreis)', 'Landkreis', 9, 72046);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9461, 'Bamberg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9, 77373);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9462, 'Bayreuth (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9, 74783);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9463, 'Coburg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9, 41072);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9464, 'Hof (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9, 45825);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9471, 'Bamberg (Landkreis)', 'Landkreis', 9, 147163);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9472, 'Bayreuth (Landkreis)', 'Landkreis', 9, 103664);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9473, 'Coburg (Landkreis)', 'Landkreis', 9, 86747);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9474, 'Forchheim (Landkreis)', 'Landkreis', 9, 116203);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9475, 'Hof (Landkreis)', 'Landkreis', 9, 94801);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9476, 'Kronach (Landkreis)', 'Landkreis', 9, 66743);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9477, 'Kulmbach (Landkreis)', 'Landkreis', 9, 71566);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9478, 'Lichtenfels (Landkreis)', 'Landkreis', 9, 66776);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9479, 'Wunsiedel i.Fichtelgebirge (Landkreis)', 'Landkreis', 9, 72655);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9561, 'Ansbach (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9, 41798);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9562, 'Erlangen (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9, 112528);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9563, 'Fürth (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9, 128497);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9564, 'Nürnberg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9, 518370);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9565, 'Schwabach (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9, 40981);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9571, 'Ansbach (Landkreis)', 'Landkreis', 9, 184591);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9572, 'Erlangen-Höchstadt (Landkreis)', 'Landkreis', 9, 137262);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9573, 'Fürth (Landkreis)', 'Landkreis', 9, 117853);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9574, 'Nürnberger Land (Landkreis)', 'Landkreis', 9, 170792);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9575, 'Neustadt a.d.Aisch-Bad Windsheim (Landkreis)', 'Landkreis', 9, 101014);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9576, 'Roth (Landkreis)', 'Landkreis', 9, 126749);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9577, 'Weißenburg-Gunzenhausen (Landkreis)', 'Landkreis', 9, 94734);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9661, 'Aschaffenburg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9, 71002);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9662, 'Schweinfurt (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9, 53426);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9663, 'Würzburg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9, 127934);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9671, 'Aschaffenburg (Landkreis)', 'Landkreis', 9, 174200);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9672, 'Bad Kissingen (Landkreis)', 'Landkreis', 9, 103235);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9673, 'Rhön-Grabfeld (Landkreis)', 'Landkreis', 9, 79635);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9674, 'Haßberge (Landkreis)', 'Landkreis', 9, 84384);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9675, 'Kitzingen (Landkreis)', 'Landkreis', 9, 91155);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9676, 'Miltenberg (Landkreis)', 'Landkreis', 9, 128743);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9677, 'Main-Spessart (Landkreis)', 'Landkreis', 9, 126158);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9678, 'Schweinfurt (Landkreis)', 'Landkreis', 9, 115445);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9679, 'Würzburg (Landkreis)', 'Landkreis', 9, 162302);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9761, 'Augsburg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9, 296582);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9762, 'Kaufbeuren (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9, 44398);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9763, 'Kempten (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9, 69151);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9764, 'Memmingen (Kreisfreie Stadt)', 'Kreisfreie Stadt', 9, 44100);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9771, 'Aichach-Friedberg (Landkreis)', 'Landkreis', 9, 134655);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9772, 'Augsburg (Landkreis)', 'Landkreis', 9, 253468);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9773, 'Dillingen a.d.Donau (Landkreis)', 'Landkreis', 9, 96562);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9774, 'Günzburg (Landkreis)', 'Landkreis', 9, 127027);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9775, 'Neu-Ulm (Landkreis)', 'Landkreis', 9, 175204);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9776, 'Lindau (Landkreis)', 'Landkreis', 9, 81981);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9777, 'Ostallgäu (Landkreis)', 'Landkreis', 9, 141182);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9778, 'Unterallgäu (Landkreis)', 'Landkreis', 9, 145341);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9779, 'Donau-Ries (Landkreis)', 'Landkreis', 9, 133783);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (9780, 'Oberallgäu (Landkreis)', 'Landkreis', 9, 156008);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (10041, 'Stadtverband Saarbrücken (Landkreis)', 'Landkreis', 10, 328714);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (10042, 'Merzig-Wadern (Landkreis)', 'Landkreis', 10, 103243);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (10043, 'Neunkirchen (Landkreis)', 'Landkreis', 10, 131408);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (10044, 'Saarlouis (Landkreis)', 'Landkreis', 10, 194319);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (10045, 'Saar-Pfalz-Kreis (Landkreis)', 'Landkreis', 10, 142196);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (10046, 'Sankt Wendel (Landkreis)', 'Landkreis', 10, 87007);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (11001, 'Berlin Mitte (Bezirk)', 'Bezirk', 11, 375238);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (11002, 'Berlin Friedrichshain-Kreuzberg (Bezirk)', 'Bezirk', 11, 282059);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (11003, 'Berlin Pankow (Bezirk)', 'Bezirk', 11, 398036);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (11004, 'Berlin Charlottenburg-Wilmersdorf (Bezirk)', 'Bezirk', 11, 334401);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (11005, 'Berlin Spandau (Bezirk)', 'Bezirk', 11, 239019);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (11006, 'Berlin Steglitz-Zehlendorf (Bezirk)', 'Bezirk', 11, 302177);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (11007, 'Berlin Tempelhof-Schöneberg (Bezirk)', 'Bezirk', 11, 341772);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (11008, 'Berlin Neukölln (Bezirk)', 'Bezirk', 11, 321123);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (11009, 'Berlin Treptow-Köpenick (Bezirk)', 'Bezirk', 11, 266488);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (11010, 'Berlin Marzahn-Hellersdorf (Bezirk)', 'Bezirk', 11, 262967);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (11011, 'Berlin Lichtenberg (Bezirk)', 'Bezirk', 11, 286522);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (11012, 'Berlin Reinickendorf (Bezirk)', 'Bezirk', 11, 259689);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (12051, 'Brandenburg a.d.Havel (Kreisfreie Stadt)', 'Kreisfreie Stadt', 12, 72184);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (12052, 'Cottbus (Kreisfreie Stadt)', 'Kreisfreie Stadt', 12, 99678);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (12053, 'Frankfurt (Oder) (Kreisfreie Stadt)', 'Kreisfreie Stadt', 12, 57751);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (12054, 'Potsdam (Kreisfreie Stadt)', 'Kreisfreie Stadt', 12, 180334);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (12060, 'Barnim (Landkreis)', 'Landkreis', 12, 185244);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (12061, 'Dahme-Spreewald (Landkreis)', 'Landkreis', 12, 170791);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (12062, 'Elbe-Elster (Landkreis)', 'Landkreis', 12, 101827);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (12063, 'Havelland (Landkreis)', 'Landkreis', 12, 162996);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (12064, 'Märkisch-Oderland (Landkreis)', 'Landkreis', 12, 195751);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (12065, 'Oberhavel (Landkreis)', 'Landkreis', 12, 212914);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (12066, 'Oberspreewald-Lausitz (Landkreis)', 'Landkreis', 12, 109371);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (12067, 'Oder-Spree (Landkreis)', 'Landkreis', 12, 178803);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (12068, 'Ostprignitz-Ruppin (Landkreis)', 'Landkreis', 12, 98861);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (12069, 'Potsdam-Mittelmark (Landkreis)', 'Landkreis', 12, 216566);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (12070, 'Prignitz (Landkreis)', 'Landkreis', 12, 76158);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (12071, 'Spree-Neiße (Landkreis)', 'Landkreis', 12, 113720);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (12072, 'Teltow-Fläming (Landkreis)', 'Landkreis', 12, 169997);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (12073, 'Uckermark (Landkreis)', 'Landkreis', 12, 118947);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (13003, 'Rostock (Kreisfreie Stadt)', 'Kreisfreie Stadt', 13, 209191);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (13004, 'Schwerin (Kreisfreie Stadt)', 'Kreisfreie Stadt', 13, 95653);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (13071, 'Mecklenburgische Seenplatte (Landkreis)', 'Landkreis', 13, 258074);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (13072, 'Rostock (Landkreis)', 'Landkreis', 13, 215794);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (13073, 'Vorpommern-Rügen (Landkreis)', 'Landkreis', 13, 224702);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (13074, 'Nordwestmecklenburg (Landkreis)', 'Landkreis', 13, 157322);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (13075, 'Vorpommern-Greifswald (Landkreis)', 'Landkreis', 13, 235623);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (13076, 'Ludwigslust-Parchim (Landkreis)', 'Landkreis', 13, 211779);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (14511, 'Chemnitz (Kreisfreie Stadt)', 'Kreisfreie Stadt', 14, 246334);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (14521, 'Erzgebirgskreis (Landkreis)', 'Landkreis', 14, 334948);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (14522, 'Mittelsachsen (Landkreis)', 'Landkreis', 14, 304099);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (14523, 'Vogtlandkreis (Landkreis)', 'Landkreis', 14, 225997);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (14524, 'Zwickau (Landkreis)', 'Landkreis', 14, 315002);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (14612, 'Dresden (Kreisfreie Stadt)', 'Kreisfreie Stadt', 14, 556780);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (14625, 'Bautzen (Landkreis)', 'Landkreis', 14, 299758);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (14626, 'Görlitz (Landkreis)', 'Landkreis', 14, 252725);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (14627, 'Meißen (Landkreis)', 'Landkreis', 14, 241717);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (14628, 'Sächsische Schweiz-Osterzgebirge (Landkreis)', 'Landkreis', 14, 245586);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (14713, 'Leipzig (Kreisfreie Stadt)', 'Kreisfreie Stadt', 14, 593145);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (14729, 'Leipzig (Landkreis)', 'Landkreis', 14, 258139);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (14730, 'Nordsachsen (Landkreis)', 'Landkreis', 14, 197741);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (15001, 'Dessau-Roßlau (Kreisfreie Stadt)', 'Kreisfreie Stadt', 15, 80103);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (15002, 'Halle (Kreisfreie Stadt)', 'Kreisfreie Stadt', 15, 238762);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (15003, 'Magdeburg (Kreisfreie Stadt)', 'Kreisfreie Stadt', 15, 237565);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (15081, 'Altmarkkreis Salzwedel (Landkreis)', 'Landkreis', 15, 83173);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (15082, 'Anhalt-Bitterfeld (Landkreis)', 'Landkreis', 15, 158486);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (15083, 'Börde (Landkreis)', 'Landkreis', 15, 170923);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (15084, 'Burgenlandkreis (Landkreis)', 'Landkreis', 15, 178846);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (15085, 'Harz (Landkreis)', 'Landkreis', 15, 213310);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (15086, 'Jerichower Land (Landkreis)', 'Landkreis', 15, 89589);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (15087, 'Mansfeld-Südharz (Landkreis)', 'Landkreis', 15, 134942);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (15088, 'Saalekreis (Landkreis)', 'Landkreis', 15, 183815);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (15089, 'Salzlandkreis (Landkreis)', 'Landkreis', 15, 189125);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (15090, 'Stendal (Landkreis)', 'Landkreis', 15, 111190);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (15091, 'Wittenberg (Landkreis)', 'Landkreis', 15, 124953);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (16051, 'Erfurt (Kreisfreie Stadt)', 'Kreisfreie Stadt', 16, 213981);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (16052, 'Gera (Kreisfreie Stadt)', 'Kreisfreie Stadt', 16, 93125);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (16053, 'Jena (Kreisfreie Stadt)', 'Kreisfreie Stadt', 16, 111343);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (16054, 'Suhl (Kreisfreie Stadt)', 'Kreisfreie Stadt', 16, 36789);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (16055, 'Weimar (Kreisfreie Stadt)', 'Kreisfreie Stadt', 16, 65228);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (16056, 'Eisenach (Kreisfreie Stadt)', 'Kreisfreie Stadt', 16, 42250);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (16061, 'Eichsfeld (Landkreis)', 'Landkreis', 16, 100006);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (16062, 'Nordhausen (Landkreis)', 'Landkreis', 16, 83416);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (16063, 'Wartburgkreis (Landkreis)', 'Landkreis', 16, 118974);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (16064, 'Unstrut-Hainich-Kreis (Landkreis)', 'Landkreis', 16, 102232);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (16065, 'Kyffhäuserkreis (Landkreis)', 'Landkreis', 16, 74212);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (16066, 'Schmalkalden-Meiningen (Landkreis)', 'Landkreis', 16, 124916);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (16067, 'Gotha (Landkreis)', 'Landkreis', 16, 134908);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (16068, 'Sömmerda (Landkreis)', 'Landkreis', 16, 69427);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (16069, 'Hildburghausen (Landkreis)', 'Landkreis', 16, 63197);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (16070, 'Ilm-Kreis (Landkreis)', 'Landkreis', 16, 106249);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (16071, 'Weimarer Land (Landkreis)', 'Landkreis', 16, 82156);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (16072, 'Sonneberg (Landkreis)', 'Landkreis', 16, 57717);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (16073, 'Saalfeld-Rudolstadt (Landkreis)', 'Landkreis', 16, 103199);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (16074, 'Saale-Holzland-Kreis (Landkreis)', 'Landkreis', 16, 82950);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (16075, 'Saale-Orla-Kreis (Landkreis)', 'Landkreis', 16, 80312);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (16076, 'Greiz (Landkreis)', 'Landkreis', 16, 97398);
INSERT INTO counties (rs, county_name, type, parent, population) VALUES (16077, 'Altenburger Land (Landkreis)', 'Landkreis', 16, 89393);